[package]
name = "exif"
version = "0.1.0"
authors = ["KAMADA Ken'ichi <kamada@nanohz.org>"]

description = "Exif parsing library written in pure Rust"
repository = "https://github.com/kamadak/exif-rs"
readme = "README"
keywords = ["Exif", "JPEG", "parser", "reader", "TIFF"]
license = "BSD-2-Clause"
